### ISSUE TITLE
createFile() fails if filename contains non URL encoded characters

### ISSUE THREAD

**Issue by mjenny** [pCloud/pcloud-sdk-java#13]
When uploading a file which contains non URL conform characters this results in a connection reset right after a couple of seconds:
```
I/chatty: uid=10156(org.cryptomator.debug) identical 7 lines
V/Progress: UPLOAD 0%
    UPLOAD 1%
I/chatty: uid=10156(org.cryptomator.debug) identical 17 lines
V/Progress: UPLOAD 1%
I/System.out: [java.net.SocketException: Connection reset, java.net.SocketException: Broken pipe, java.net.SocketException: Broken pipe, java.net.SocketException: Broken pipe, java.net.SocketException: Broken pipe, java.net.SocketException: Broken pipe, java.net.SocketException: Broken pipe]
D/OkHttp: <-- HTTP FAILED: java.net.SocketException: Broken pipe
D/UploadFilesUseCase: failed 44a959d8
D/BackgroundTasks: type:0 all:0 unregister@ org.cryptomator.domain.usecases.cloud.UploadFilesUseCase$Launcher$2#subscribe:126
D/ExceptionHandler: 			Unexpected error
    org.cryptomator.domain.exception.NetworkConnectionException: org.cryptomator.domain.exception.FatalBackendException: java.net.SocketException: Broken pipe
        at org.cryptomator.data.cloud.pcloud.PCloudContentRepository.throwConnectionErrorIfRequired(PCloudContentRepository.java:46)
        at org.cryptomator.data.cloud.pcloud.PCloudContentRepository.throwWrappedIfRequired(PCloudContentRepository.java:40)
        at org.cryptomator.data.cloud.InterceptingCloudContentRepository.write(InterceptingCloudContentRepository.java:167)
        at org.cryptomator.data.repository.DispatchingCloudContentRepository.write(DispatchingCloudContentRepository.java:165)
        at org.cryptomator.data.cloud.crypto.CryptoImplDecorator.writeFromTmpFile(CryptoImplDecorator.java:249)
        at org.cryptomator.data.cloud.crypto.CryptoImplDecorator.writeShortNameFile(CryptoImplDecorator.java:413)
        at org.cryptomator.data.cloud.crypto.CryptoImplVaultFormat7.write(CryptoImplVaultFormat7.java:462)
        at org.cryptomator.data.cloud.crypto.CryptoCloudContentRepository.write(CryptoCloudContentRepository.java:113)
        at org.cryptomator.data.cloud.crypto.CryptoCloudContentRepository.write(CryptoCloudContentRepository.java:24)
        at org.cryptomator.data.repository.DispatchingCloudContentRepository.write(DispatchingCloudContentRepository.java:165)
        at org.cryptomator.domain.usecases.cloud.UploadFiles.writeCloudFile(UploadFiles.java:118)
        at org.cryptomator.domain.usecases.cloud.UploadFiles.upload(UploadFiles.java:95)
        at org.cryptomator.domain.usecases.cloud.UploadFiles.upload(UploadFiles.java:83)
        at org.cryptomator.domain.usecases.cloud.UploadFiles.upload(UploadFiles.java:75)
        at org.cryptomator.domain.usecases.cloud.UploadFiles.execute(UploadFiles.java:62)
        at org.cryptomator.domain.usecases.cloud.UploadFilesUseCase$Launcher$2.subscribe(UploadFilesUseCase.java:119)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.Flowable.subscribe(Flowable.java:14882)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    Caused by: org.cryptomator.domain.exception.FatalBackendException: java.net.SocketException: Broken pipe
        at org.cryptomator.data.cloud.pcloud.PCloudContentRepository$Intercepted.write(PCloudContentRepository.java:166)
        at org.cryptomator.data.cloud.pcloud.PCloudContentRepository$Intercepted.write(PCloudContentRepository.java:56)
        at org.cryptomator.data.cloud.InterceptingCloudContentRepository.write(InterceptingCloudContentRepository.java:162)
    	... 22 more
    Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeToSocket(ConscryptEngineSocket.java:715)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:689)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.write(ConscryptEngineSocket.java:652)
        at okio.OutputStreamSink.write(JvmOkio.kt:53)
        at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
        at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
        at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
        at okio.ForwardingSink.write(ForwardingSink.kt:29)
        at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
        at okio.RealBufferedSink.write(RealBufferedSink.kt:146)
        at okio.ForwardingSink.write(ForwardingSink.kt:29)
        at com.pcloud.sdk.internal.ProgressCountingSink.write(ProgressCountingSink.java:43)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
        at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
        at org.cryptomator.data.cloud.pcloud.PCloudImpl$1.writeTo(PCloudImpl.java:264)
        at com.pcloud.sdk.internal.RealApiClient$5.writeTo(RealApiClient.java:270)
        at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
        at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.cryptomator.data.cloud.okhttplogging.HttpLoggingInterceptor.getResponseLoggingExceptions(HttpLoggingInterceptor.java:77)
        at org.cryptomator.data.cloud.okhttplogging.HttpLoggingInterceptor.getAndLogResponse(HttpLoggingInterceptor.java:69)
        at org.cryptomator.data.cloud.okhttplogging.HttpLoggingInterceptor.proceedWithLogging(HttpLoggingInterceptor.java:57)
        at org.cryptomator.data.cloud.okhttplogging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:48)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.pcloud.sdk.internal.AccessTokenAuthenticator.intercept(AccessTokenAuthenticator.java:48)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.pcloud.sdk.internal.GlobalRequestInterceptor.intercept(GlobalRequestInterceptor.java:44)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.pcloud.sdk.internal.OkHttpCall.execute(OkHttpCall.java:40)
        at org.cryptomator.data.cloud.pcloud.PCloudImpl.uploadFile(PCloudImpl.java:276)
        at org.cryptomator.data.cloud.pcloud.PCloudImpl.write(PCloudImpl.java:240)
        at org.cryptomator.data.cloud.pcloud.PCloudContentRepository$Intercepted.write(PCloudContentRepository.java:161)
    	... 24 more
    	Suppressed: java.net.SocketException: Connection reset
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:121)
    		... 70 more
    	Suppressed: java.net.SocketException: Broken pipe
    		... 72 more
    	Suppressed: java.net.SocketException: Broken pipe
    		... 72 more
    	Suppressed: java.net.SocketException: Broken pipe
    		... 72 more
    	Suppressed: java.net.SocketException: Broken pipe
    		... 72 more
    	Suppressed: java.net.SocketException: Broken pipe
    		... 72 more
    	Suppressed: java.net.SocketException: Broken pipe
D/ExceptionHandler: 		... 72 more
    			ErrorCode: F33B:FJE4
```
An example would be a file with name `YYbfUTn6ViuRkXzeXXYAAu8z6DwFMrTNtPY3zpjn24RIUmzqqi4=.c9r` the `=` being the issue. Encoded (`YYbfUTn6ViuRkXzeXXYAAu8z6DwFMrTNtPY3zpjn24RIUmzqqi4%3D.c9r`) the upload works without any issues.

**Comment by georgi-neykov-hub** [comment]
@mjenny there is an API bug which does not escape properly the `=` symbol and ignores the form-data for the file. There's a fix from the API team which will become live after one of the deployment windows next week.

**Comment by mjenny** [comment]
It seems that this issue is resolved.
