### ISSUE TITLE
Upload file error in thread "main" java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Bassamm0** [pCloud/pcloud-sdk-java#2]
Hi I got this error when I try to upload file to Cloud

Exception in thread "main" java.lang.IncompatibleClassChangeError
	at com.pcloud.sdk.internal.IOUtils.closeQuietly(IOUtils.java:29)
	at com.pcloud.sdk.internal.RealApiClient.deserializeResponseBody(RealApiClient.java:950)
	at com.pcloud.sdk.internal.RealApiClient.getAsApiResponse(RealApiClient.java:924)
	at com.pcloud.sdk.internal.RealApiClient.access$000(RealApiClient.java:52)
	at com.pcloud.sdk.internal.RealApiClient$3.adapt(RealApiClient.java:228)
	at com.pcloud.sdk.internal.RealApiClient$3.adapt(RealApiClient.java:225)
	at com.pcloud.sdk.internal.OkHttpCall.adapt(OkHttpCall.java:99)
	at com.pcloud.sdk.internal.OkHttpCall.execute(OkHttpCall.java:41)

any idea how to solve it

Thank you

**Comment by georgi-neykov-hub** [comment]
Hello @Bassamm0,

Can you please give more insight on the problem:
* What version of the SDK are you using
* What platform are you running on (JVM, Android)

Thank you

**Comment by georgi-neykov-hub** [comment]
Is there any chance you are getting the error while running the SDK on an pre-API19 Android device?
If the answer is yes, I suspect that the cause is the same as described in /square/okhttp/#3125, basically Android's pre-Kit Kat `Socket` does not implement `Closeable` even though it has a `close()` method and the online documentation states it inherits it.

And yet, the SDK's `closeQuietly()` expects a `Closeable` and OkHttp's `Response` which is what's getting closed at [RealApiClient.java#L950](https://github.com/pCloud/pcloud-sdk-java/blob/master/java-core/src/main/java/com/pcloud/sdk/internal/RealApiClient.java#L950) and it definitely implements `Closeable`.

You may as well check your project's dependency graph for version conflicts related to OkHttp.
