### ISSUE TITLE
TLS certificate of vc734.pcloud.com has expired which does not allow a connection and therefore no file download

### ISSUE THREAD

**Issue by SailReal** [pCloud/pcloud-sdk-java#36]
A user of our Cryptomator app which connects to pCloud reports: When downloading a file, a network exception is thrown with the following connection log: 

```
OkHttp	--> GET https://api.pcloud.com/stat?path=/Chad%20Files/vault.cryptomator http/1.1 (unknown length)
OkHttp	User-Agent: pCloud SDK Java unspecified
OkHttp	--> END GET
OkHttp	<-- 200 OK https://api.pcloud.com/stat?path=/Chad%20Files/vault.cryptomator (482ms)
OkHttp	Server: CloudHTTPd-API v1.1
OkHttp	Date: Mon, 04 Apr 2022 18:33:30 GMT
OkHttp	ETag: "MHYJf8ezi3hERQA785P9bHIhDffX"
OkHttp	Cache-Control: private, max-age=0
OkHttp	Vary: Accept-Encoding
OkHttp	Connection: keep-alive
OkHttp	Keep-Alive: timeout=1800
OkHttp	<-- END HTTP
OkHttp	--> GET https://api.pcloud.com/getfilelink?path=/Chad%20Files/vault.cryptomator http/1.1 (unknown length)
OkHttp	User-Agent: pCloud SDK Java unspecified
OkHttp	--> END GET
OkHttp	<-- 200 OK https://api.pcloud.com/getfilelink?path=/Chad%20Files/vault.cryptomator (95ms)
OkHttp	Server: CloudHTTPd-API v1.1
OkHttp	Date: Mon, 04 Apr 2022 18:33:30 GMT
OkHttp	ETag: "pAxLB4axcuXCvFJt2PuX3h2WJWRk"
OkHttp	Cache-Control: private, max-age=0
OkHttp	Vary: Accept-Encoding
OkHttp	Connection: keep-alive
OkHttp	Keep-Alive: timeout=1800
OkHttp	<-- END HTTP
OkHttp	--> GET https://vc734.pcloud.com/dpZxUAMITZGWEQX6ZcMAm7ZZgjW5r7Z2ZZTH5ZZ3CsAFwVu8IzuWab5jdH73ppqxTLV/vault.cryptomator http/1.1 (unknown length)
OkHttp	User-Agent: pCloud SDK Java unspecified
OkHttp	--> END GET
OkHttp	<-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: Chain validation failed
GetUnverifiedVaultConfigUseCase	failed 75da80d9
ExceptionHandler	Unexpected error
org.cryptomator.domain.exception.NetworkConnectionException: org.cryptomator.domain.exception.FatalBackendException: javax.net.ssl.SSLHandshakeException: Chain validation failed
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository.throwConnectionErrorIfRequired(PCloudContentRepository.kt:32)
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository.throwWrappedIfRequired(PCloudContentRepository.kt:25)
	at org.cryptomator.data.cloud.InterceptingCloudContentRepository.read(InterceptingCloudContentRepository.kt:173)
	at org.cryptomator.data.repository.DispatchingCloudContentRepository.read(DispatchingCloudContentRepository.kt:160)
	at org.cryptomator.data.cloud.crypto.CryptoCloudFactory.readConfigFileData(CryptoCloudFactory.java:59)
	at org.cryptomator.data.cloud.crypto.CryptoCloudFactory.unverifiedVaultConfig(CryptoCloudFactory.java:52)
	at org.cryptomator.data.repository.CloudRepositoryImpl.unverifiedVaultConfig(CloudRepositoryImpl.java:96)
	at org.cryptomator.domain.usecases.vault.GetUnverifiedVaultConfig.execute(GetUnverifiedVaultConfig.java:28)
	at org.cryptomator.domain.usecases.vault.GetUnverifiedVaultConfigUseCase$Launcher$2.call(GetUnverifiedVaultConfigUseCase.java:92)
	at org.cryptomator.domain.usecases.vault.GetUnverifiedVaultConfigUseCase$Launcher$2.call(GetUnverifiedVaultConfigUseCase.java:86)
	at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:39)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: org.cryptomator.domain.exception.FatalBackendException: javax.net.ssl.SSLHandshakeException: Chain validation failed
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository$Intercepted.read(PCloudContentRepository.kt:150)
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository$Intercepted.read(PCloudContentRepository.kt:47)
	at org.cryptomator.data.cloud.InterceptingCloudContentRepository.read(InterceptingCloudContentRepository.kt:168)
	... 16 more
Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.cryptomator.data.cloud.okhttplogging.HttpLoggingInterceptor.getResponseLoggingExceptions(HttpLoggingInterceptor.kt:51)
	at org.cryptomator.data.cloud.okhttplogging.HttpLoggingInterceptor.getAndLogResponse(HttpLoggingInterceptor.kt:42)
	at org.cryptomator.data.cloud.okhttplogging.HttpLoggingInterceptor.proceedWithLogging(HttpLoggingInterceptor.kt:28)
	at org.cryptomator.data.cloud.okhttplogging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:18)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.pcloud.sdk.internal.AccessTokenAuthenticator.intercept(AccessTokenAuthenticator.java:50)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.pcloud.sdk.internal.GlobalRequestInterceptor.intercept(GlobalRequestInterceptor.java:46)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.pcloud.sdk.internal.OkHttpCall.execute(OkHttpCall.java:42)
	at org.cryptomator.data.cloud.pcloud.PCloudImpl.writeToData(PCloudImpl.kt:274)
	at org.cryptomator.data.cloud.pcloud.PCloudImpl.read(PCloudImpl.kt:246)
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository$Intercepted.read(PCloudContentRepository.kt:148)
	... 18 more
Caused by: java.security.cert.CertificateException: Chain validation failed
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:719)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:570)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:638)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	... 55 more
Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:715)
	... 70 more
Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Fri Mar 11 09:52:00 CST 2022 (compared to Mon Apr 04 13:33:33 CDT 2022)
	at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:269)
	at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 75 more

ErrorCode: L2G5:QI9I
```
It looks like the TLS certificate of  https://vc734.pcloud.com isn't valid anymore.

I also reproduced it using `curl`:

```
curl -I https://vc734.pcloud.com/dpZxUAMITZGWEQX6ZcMAm7ZZgjW5r7Z2ZZTH5ZZ3CsAFwVu8IzuWab5jdH73ppqxTLV/vault.cryptomator -v -k                                                                    60 ✘
*   Trying 199.7.176.89:443...
* Connected to vc734.pcloud.com (199.7.176.89) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=CH; ST=Zug; L=Baar; O=pCloud AG; CN=*.pcloud.com
*  start date: Mar 11 15:42:34 2020 GMT
*  expire date: Mar 11 15:52:00 2022 GMT
*  issuer: C=BM; O=QuoVadis Limited; CN=QuoVadis Global SSL ICA G2
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> HEAD /dpZxUAMITZGWEQX6ZcMAm7ZZgjW5r7Z2ZZTH5ZZ3CsAFwVu8IzuWab5jdH73ppqxTLV/vault.cryptomator HTTP/1.1
> Host: vc734.pcloud.com
> User-Agent: curl/7.82.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 410 Gone
HTTP/1.1 410 Gone
< Server: CloudHTTPd v1.1
Server: CloudHTTPd v1.1
< Date: Mon, 04 Apr 2022 22:09:00 +0000
Date: Mon, 04 Apr 2022 22:09:00 +0000
< Content-Type: text/html
Content-Type: text/html
< Content-Length: 4096
Content-Length: 4096
< Connection: close
Connection: close

<
* Closing connection 0
* TLSv1.3 (IN), TLS alert, close notify (256):
* TLSv1.3 (OUT), TLS alert, close notify (256):
```

**Comment by overheadhunter** [comment]
Kindly brought to you by: Logging.

\*cough\* pCloud/pcloud-sdk-java#14

**Comment by gogogohub** [comment]
I think this issue has been resolved.

**Comment by SailReal** [comment]
@georgi-neykov-hub closed without any reaction?
