### ISSUE TITLE
Downloading files sometimes fails with HTTP status code `410`

### ISSUE THREAD

**Issue by SailReal** [pCloud/pcloud-sdk-java#39]
A user reported, when connected to WiFi, sometimes a file can not be downloaded. Looking through the log I often see something like this:

```
20220816121532.811	OkHttp	--> GET https://eapi.pcloud.com/stat?path=/Trezor/vault.cryptomator http/1.1 (unknown length)
20220816121532.811	OkHttp	User-Agent: pCloud SDK Java unspecified
20220816121532.811	OkHttp	--> END GET
20220816121532.916	OkHttp	<-- 200 OK https://eapi.pcloud.com/stat?path=/Trezor/vault.cryptomator (105ms)
20220816121532.917	OkHttp	Server: CloudHTTPd-API v1.1
20220816121532.918	OkHttp	Date: Tue, 16 Aug 2022 10:15:31 GMT
20220816121532.919	OkHttp	ETag: "DdCOe4wWNEzXi6PhAbo7tbbM5oy7"
20220816121532.919	OkHttp	Cache-Control: private, max-age=0
20220816121532.924	OkHttp	Vary: Accept-Encoding
20220816121532.924	OkHttp	Connection: keep-alive
20220816121532.925	OkHttp	Keep-Alive: timeout=1800
20220816121532.925	OkHttp	<-- END HTTP
20220816121532.927	OkHttp	--> GET https://eapi.pcloud.com/getfilelink?path=/Trezor/vault.cryptomator http/1.1 (unknown length)
20220816121532.928	OkHttp	User-Agent: pCloud SDK Java unspecified
20220816121532.928	OkHttp	--> END GET
20220816121532.989	OkHttp	<-- 200 OK https://eapi.pcloud.com/getfilelink?path=/Trezor/vault.cryptomator (60ms)
20220816121532.990	OkHttp	Server: CloudHTTPd-API v1.1
20220816121532.991	OkHttp	Date: Tue, 16 Aug 2022 10:15:31 GMT
20220816121532.991	OkHttp	ETag: "INM57mRMmY7yIts8rUUQiYMJpytk"
20220816121532.991	OkHttp	Cache-Control: private, max-age=0
20220816121532.992	OkHttp	Vary: Accept-Encoding
20220816121532.992	OkHttp	Connection: keep-alive
20220816121532.992	OkHttp	Keep-Alive: timeout=1800
20220816121532.992	OkHttp	<-- END HTTP
20220816121532.995	OkHttp	--> GET https://evc132.pcloud.com/dpZfYLrhzZe3tmCmZkRWRZZ16bir7Z2ZZYn0ZZITMQacS5AyHuV1chtR1uFHBWTKAk/vault.cryptomator http/1.1 (unknown length)
20220816121532.995	OkHttp	User-Agent: pCloud SDK Java unspecified
20220816121532.995	OkHttp	--> END GET
20220816121533.265	OkHttp	<-- 410 Gone https://evc132.pcloud.com/dpZfYLrhzZe3tmCmZkRWRZZ16bir7Z2ZZYn0ZZITMQacS5AyHuV1chtR1uFHBWTKAk/vault.cryptomator (269ms)
20220816121533.267	OkHttp	Server: CloudHTTPd v1.1
20220816121533.267	OkHttp	Date: Tue, 16 Aug 2022 10:15:31 +0000
20220816121533.267	OkHttp	Connection: keep-alive
20220816121533.267	OkHttp	Keep-Alive: timeout=30
20220816121533.268	OkHttp	<-- END HTTP
20220816121533.270	GetUnverifiedVaultConfigUseCase	failed 2622aeb6
20220816121533.271	ExceptionHandler	Unexpected error
org.cryptomator.domain.exception.NetworkConnectionException: org.cryptomator.domain.exception.FatalBackendException: com.pcloud.sdk.internal.networking.APIHttpException: API returned '410 - Gone' HTTP error.
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository.throwConnectionErrorIfRequired(PCloudContentRepository.kt:32)
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository.throwWrappedIfRequired(PCloudContentRepository.kt:25)
	at org.cryptomator.data.cloud.InterceptingCloudContentRepository.read(InterceptingCloudContentRepository.kt:173)
	at org.cryptomator.data.repository.DispatchingCloudContentRepository.read(DispatchingCloudContentRepository.kt:160)
	at org.cryptomator.data.cloud.crypto.CryptoCloudFactory.readConfigFileData(CryptoCloudFactory.java:59)
	at org.cryptomator.data.cloud.crypto.CryptoCloudFactory.unverifiedVaultConfig(CryptoCloudFactory.java:52)
	at org.cryptomator.data.repository.CloudRepositoryImpl.unverifiedVaultConfig(CloudRepositoryImpl.java:97)
	at org.cryptomator.domain.usecases.vault.GetUnverifiedVaultConfig.execute(GetUnverifiedVaultConfig.java:28)
	at org.cryptomator.domain.usecases.vault.GetUnverifiedVaultConfigUseCase$Launcher$2.call(GetUnverifiedVaultConfigUseCase.java:92)
	at org.cryptomator.domain.usecases.vault.GetUnverifiedVaultConfigUseCase$Launcher$2.call(GetUnverifiedVaultConfigUseCase.java:86)
	at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:39)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: org.cryptomator.domain.exception.FatalBackendException: com.pcloud.sdk.internal.networking.APIHttpException: API returned '410 - Gone' HTTP error.
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository$Intercepted.read(PCloudContentRepository.kt:150)
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository$Intercepted.read(PCloudContentRepository.kt:47)
	at org.cryptomator.data.cloud.InterceptingCloudContentRepository.read(InterceptingCloudContentRepository.kt:168)
	... 16 more
Caused by: com.pcloud.sdk.internal.networking.APIHttpException: API returned '410 - Gone' HTTP error.
	at com.pcloud.sdk.internal.RealApiClient.getAsRawBytes(RealApiClient.java:1230)
	at com.pcloud.sdk.internal.RealApiClient.lambda$download$5$com-pcloud-sdk-internal-RealApiClient(RealApiClient.java:499)
	at com.pcloud.sdk.internal.RealApiClient$$ExternalSyntheticLambda19.adapt(Unknown Source:6)
	at com.pcloud.sdk.internal.OkHttpCall.adapt(OkHttpCall.java:101)
	at com.pcloud.sdk.internal.OkHttpCall.execute(OkHttpCall.java:43)
	at org.cryptomator.data.cloud.pcloud.PCloudImpl.writeToData(PCloudImpl.kt:274)
	at org.cryptomator.data.cloud.pcloud.PCloudImpl.read(PCloudImpl.kt:246)
	at org.cryptomator.data.cloud.pcloud.PCloudContentRepository$Intercepted.read(PCloudContentRepository.kt:148)
	... 18 more
ErrorCode: L2G5:KMOT
```

Where as some minutes later (10 in this case) it works again: 

```
20220816121542.824	OkHttp	--> GET https://eapi.pcloud.com/stat?path=/Trezor/vault.cryptomator http/1.1 (unknown length)
20220816121542.824	OkHttp	User-Agent: pCloud SDK Java unspecified
20220816121542.824	OkHttp	--> END GET
20220816121542.933	OkHttp	<-- 200 OK https://eapi.pcloud.com/stat?path=/Trezor/vault.cryptomator (108ms)
20220816121542.934	OkHttp	Server: CloudHTTPd-API v1.1
20220816121542.934	OkHttp	Date: Tue, 16 Aug 2022 10:15:41 GMT
20220816121542.934	OkHttp	ETag: "DdCOe4wWNEzXi6PhAbo7tbbM5oy7"
20220816121542.934	OkHttp	Cache-Control: private, max-age=0
20220816121542.934	OkHttp	Vary: Accept-Encoding
20220816121542.934	OkHttp	Connection: keep-alive
20220816121542.935	OkHttp	Keep-Alive: timeout=1800
20220816121542.935	OkHttp	<-- END HTTP
20220816121542.937	OkHttp	--> GET https://eapi.pcloud.com/getfilelink?path=/Trezor/vault.cryptomator http/1.1 (unknown length)
20220816121542.937	OkHttp	User-Agent: pCloud SDK Java unspecified
20220816121542.937	OkHttp	--> END GET
20220816121542.993	OkHttp	<-- 200 OK https://eapi.pcloud.com/getfilelink?path=/Trezor/vault.cryptomator (55ms)
20220816121542.993	OkHttp	Server: CloudHTTPd-API v1.1
20220816121542.994	OkHttp	Date: Tue, 16 Aug 2022 10:15:41 GMT
20220816121542.994	OkHttp	ETag: "MEqnm5XExfy0ig4JYtn5eVzU7RVy"
20220816121542.994	OkHttp	Cache-Control: private, max-age=0
20220816121542.994	OkHttp	Vary: Accept-Encoding
20220816121542.994	OkHttp	Connection: keep-alive
20220816121542.994	OkHttp	Keep-Alive: timeout=1800
20220816121542.994	OkHttp	<-- END HTTP
20220816121542.996	OkHttp	--> GET https://evc212.pcloud.com/dpZfYLrhzZe3tmCmZkRWRZZw6bir7Z2ZZYn0ZZrl21nD7mafkm2xGbegIKk0NlqOWk/vault.cryptomator http/1.1 (unknown length)
20220816121542.996	OkHttp	User-Agent: pCloud SDK Java unspecified
20220816121542.996	OkHttp	--> END GET
20220816121543.346	OkHttp	<-- 200 OK https://evc212.pcloud.com/dpZfYLrhzZe3tmCmZkRWRZZw6bir7Z2ZZYn0ZZrl21nD7mafkm2xGbegIKk0NlqOWk/vault.cryptomator (349ms)
20220816121543.347	OkHttp	Server: CloudHTTPd v1.1
20220816121543.348	OkHttp	Date: Tue, 16 Aug 2022 10:15:41 +0000
20220816121543.348	OkHttp	Etag: "d85ebfffc31e6f5cc664ff2d0b8c6e9c91e8a246"
20220816121543.348	OkHttp	Last-Modified: Thu, 11 Aug 2022 13:49:11 +0000
20220816121543.348	OkHttp	Expires: Tue, 16 Aug 2022 16:15:41 +0000
20220816121543.348	OkHttp	Content-Disposition: attachment; filename="vault.cryptomator"
20220816121543.348	OkHttp	Accept-Ranges: bytes
20220816121543.349	OkHttp	Content-Transfer-Encoding: binary
20220816121543.349	OkHttp	Connection: keep-alive
20220816121543.349	OkHttp	Keep-Alive: timeout=30
20220816121543.349	OkHttp	<-- END HTTP
```

I have no idea why we get a file link in the first case but then the server returns a `410 Gone` some milliseconds later when downloading it.

**Comment by SailReal** [comment]
@georgi-neykov-hub can you give us some feedback?

**Comment by sixtsense** [comment]
Hello, and sorry for the delayed response. I took a look at the provided Exception log in this and the #40 issue. In both of them you are calling the`RealApiClient.download` method supplying it with a FileLink. Is the provided FileLink generated immediately before the `download` call ? If not and the FileLink has been generated prior to the `download` call there is a high possibility that the link would have expired.

**Comment by SailReal** [comment]
@sixtsense you can see in the log timestamps, the file link was generated at request time `20220816121532.927`, response time `20220816121532.989` and downloaded at request time `20220816121532.995` response time `20220816121533.265`.

So between the response time of the file link request and the request time of the download call are 6ms. Response of file link to response of download call is 267ms.

In issue #40 it is 357ms from download file link response to download file response.

I don't think a file link should expire in that small amount of time.

**Comment by LearningAsIGo71** [comment]
Is this going to be resolved? It is affecting my use of pCloud.

**Comment by SailReal** [comment]
@sixtsense do you have any news for us regarding this topic? Can we somehow help to troubleshoot the problem?

**Comment by georgi-neykov-hub** [comment]
> @sixtsense do you have any news for us regarding this topic? Can we somehow help to troubleshoot the problem?

@SailReal , I've commented on the issue with Cryptomator's behavior in the referenced issue, closing and moving the discussion there.
